In [4]:
#!pip install Pipeline
from sklearn.pipeline import Pipeline

In [5]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [6]:
steps=[("StandardScaler",StandardScaler()),
        ("classifier",LogisticRegression())
]

In [7]:
steps

[('StandardScaler', StandardScaler()), ('classifier', LogisticRegression())]

In [8]:
pipe=Pipeline(steps)

In [9]:
from sklearn import set_config

In [10]:
pipe

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [11]:
from sklearn.datasets import make_classification
X,y =make_classification(n_samples=1000)

In [12]:
X.shape

(1000, 20)

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [15]:
X_train

array([[ 1.16947232, -0.72405611, -1.41029279, ..., -0.63713912,
        -0.83670637, -0.54304078],
       [-0.45426896,  0.42642522, -1.08392275, ...,  0.1231657 ,
        -0.03486206, -0.11954823],
       [-1.95245607, -1.30820003, -0.11988188, ..., -0.92308903,
         0.81069109,  0.29856523],
       ...,
       [ 0.12014896,  1.0102788 , -0.42247344, ...,  0.79709219,
         0.62168854, -0.49354294],
       [ 0.27337131, -0.41300871, -0.26867247, ..., -0.39750262,
         1.75741277,  1.87573625],
       [-0.02500521, -1.64391129,  1.57440284, ..., -1.06774393,
         0.01402306,  0.07924549]])

In [16]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('StandardScaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [17]:
y_pred=pipe.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1])

In [18]:
from sklearn.decomposition import PCA 
from sklearn.svm import SVC

In [19]:
steps=[("scaling", StandardScaler()),("PCA",PCA(n_components=3)),("SVC",SVC())]

In [20]:
steps

[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)), ('SVC', SVC())]

In [21]:
pipe2=Pipeline(steps)

In [22]:
pipe2.fit(X_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('SVC', SVC())])

In [23]:
pipe2.predict(X_test)

array([0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1])

# column transform example

In [24]:
from sklearn.impute import SimpleImputer

In [27]:
import numpy as np
#numericl pipeline
numeric_processor =Pipeline(
    steps=[("imputatioin_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),("scaler",StandardScaler())]
)

In [28]:
numeric_processor

Pipeline(steps=[('imputatioin_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [35]:
#categorical pipeline
from sklearn.preprocessing import OneHotEncoder
cat_processor =Pipeline(
    steps=[("imputatioin_constant",SimpleImputer(fill_value="missing",strategy="constant")),("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [34]:
cat_processor

Pipeline(steps=[('imputatioin_constant',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('scaler', StandardScaler())])

In [36]:
from sklearn.compose import ColumnTransformer

In [39]:
preprocessor=ColumnTransformer(
    [("categorial",cat_processor,["gender","city"]),
    ("numeric",numeric_processor,["age","height"])]
)

In [40]:
preprocessor

ColumnTransformer(transformers=[('categorial',
                                 Pipeline(steps=[('imputatioin_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numeric',
                                 Pipeline(steps=[('imputatioin_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [41]:
from sklearn.pipeline import make_pipeline

In [44]:
pipe =make_pipeline(preprocessor,LogisticRegression())
pipe

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorial',
                                                  Pipeline(steps=[('imputatioin_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numeric',
                                                  Pipeline(steps=[('imputatioin_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])