In [1]:
import numpy as np

In [7]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9.3],[0,3,6]])
arr

array([[1. , 2. , 3. ],
       [4. , 5. , 6. ],
       [7. , 8. , 9.3],
       [0. , 3. , 6. ]])

In [8]:
arr.shape

(4, 3)

In [9]:
arr.size

12

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr.tolist()

[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.3], [0.0, 3.0, 6.0]]

In [12]:
a=4

In [13]:
print("address of A:",id(a))
b=a
print("address of B:",id(b))
c=np.copy(a)
print("address of c:",id(c))

address of A: 140704649848720
address of B: 140704649848720
address of c: 2906316301584


In [14]:
arr=np.array([[3,2,6],[9,8,6]])
arr
print("address of arr:",id(arr))
arr1=arr
print("address of arr1:",id(arr1))
arr2=np.copy(arr)
print("address of arr2:",id(arr2))

address of arr: 2906316300432
address of arr1: 2906316300432
address of arr2: 2906316300624


In [15]:
arr=np.array([[3,2,5,9,8]])
arr

array([[3, 2, 5, 9, 8]])

In [16]:
np.sort(arr)

array([[2, 3, 5, 8, 9]])

In [18]:
arr =np.array([[3,2,5],[6,8,5]])
arr
np.sort(arr)

array([[2, 3, 5],
       [5, 6, 8]])

In [19]:
arr=np.array([["siva",22,69,8,"abc",36]])
np.sort(arr)

array([['22', '36', '69', '8', 'abc', 'siva']], dtype='<U11')

In [20]:
arr=np.array([[3,2,5],[11,8,6],[9,5,6]])
arr

array([[ 3,  2,  5],
       [11,  8,  6],
       [ 9,  5,  6]])

In [21]:
arr.flatten()

array([ 3,  2,  5, 11,  8,  6,  9,  5,  6])

In [22]:
arr.T

array([[ 3, 11,  9],
       [ 2,  8,  5],
       [ 5,  6,  6]])

In [25]:
arr.reshape(3,3)

array([[ 3,  2,  5],
       [11,  8,  6],
       [ 9,  5,  6]])

In [33]:
np.resize(arr,(6,6))

array([[ 3,  2,  5, 11,  8,  6],
       [ 9,  5,  6,  3,  2,  5],
       [11,  8,  6,  9,  5,  6],
       [ 3,  2,  5, 11,  8,  6],
       [ 9,  5,  6,  3,  2,  5],
       [11,  8,  6,  9,  5,  6]])

adding removing data

In [34]:
arr=np.array([[2,3,5,6],[6,8,2,9],[55,22,6,7],[88,66,77,22]])
arr

array([[ 2,  3,  5,  6],
       [ 6,  8,  2,  9],
       [55, 22,  6,  7],
       [88, 66, 77, 22]])

In [35]:
arr1=np.append(arr,[20,30,40,50])

In [36]:
arr1.reshape(5,4)

array([[ 2,  3,  5,  6],
       [ 6,  8,  2,  9],
       [55, 22,  6,  7],
       [88, 66, 77, 22],
       [20, 30, 40, 50]])

In [43]:
arr1=np.insert(arr,6,[60,70,80,90])

In [44]:
arr1.reshape(5,4)

array([[ 2,  3,  5,  6],
       [ 6,  8, 60, 70],
       [80, 90,  2,  9],
       [55, 22,  6,  7],
       [88, 66, 77, 22]])

In [47]:
arr1=np.delete(arr,1,axis=0)
arr1

array([[ 2,  3,  5,  6],
       [55, 22,  6,  7],
       [88, 66, 77, 22]])

In [48]:
np.delete(arr,2,axis=1)

array([[ 2,  3,  6],
       [ 6,  8,  9],
       [55, 22,  7],
       [88, 66, 22]])