In [1]:
import numpy as np

In [2]:
arr=np.array([[3,2,6,8],[6,8,2,3],[8,6,7,2],[0,6,8,2]])
arr1=np.array([[3,6,9,5],[22,6,7,9],[66,8,2,5]])
arr2=np.array([[3,6,7,2],[3,8,2,4],[22,44,66,88],[7,0,5,9]])

In [3]:
np.concatenate((arr,arr1),axis=0)

array([[ 3,  2,  6,  8],
       [ 6,  8,  2,  3],
       [ 8,  6,  7,  2],
       [ 0,  6,  8,  2],
       [ 3,  6,  9,  5],
       [22,  6,  7,  9],
       [66,  8,  2,  5]])

In [4]:
np.concatenate((arr,arr2),axis=0)

array([[ 3,  2,  6,  8],
       [ 6,  8,  2,  3],
       [ 8,  6,  7,  2],
       [ 0,  6,  8,  2],
       [ 3,  6,  7,  2],
       [ 3,  8,  2,  4],
       [22, 44, 66, 88],
       [ 7,  0,  5,  9]])

In [5]:
arr=np.array([[3,6,7,2],[3,8,2,4],[22,44,66,88],[7,0,5,9]])

In [6]:
np.split(arr,2)

[array([[3, 6, 7, 2],
        [3, 8, 2, 4]]),
 array([[22, 44, 66, 88],
        [ 7,  0,  5,  9]])]

In [7]:
arr=np.array([[3,6,7,2],[3,8,2,4],[22,44,66,88],[7,0,5,9],[22,66,33,55],[88,55,66,44],[77,22,99,44]])

In [8]:
np.hsplit(arr,4)

[array([[ 3],
        [ 3],
        [22],
        [ 7],
        [22],
        [88],
        [77]]),
 array([[ 6],
        [ 8],
        [44],
        [ 0],
        [66],
        [55],
        [22]]),
 array([[ 7],
        [ 2],
        [66],
        [ 5],
        [33],
        [66],
        [99]]),
 array([[ 2],
        [ 4],
        [88],
        [ 9],
        [55],
        [44],
        [44]])]

In [9]:
arr =np.array([3,2,6,5,9,12])
arr1=np.array([[12,19,3,4,16,18],[2,1,23,4,25,26]])

In [10]:
arr[4]

9

In [11]:
arr1[1,3]

4

In [12]:
arr[1]=9
arr

array([ 3,  9,  6,  5,  9, 12])

In [13]:
arr1[1,4]=10
arr1

array([[12, 19,  3,  4, 16, 18],
       [ 2,  1, 23,  4, 10, 26]])

In [14]:
arr[:3]

array([3, 9, 6])

In [15]:
arr1[0:2,0:1]

array([[12],
       [ 2]])

In [16]:
arr1[:1]

array([[12, 19,  3,  4, 16, 18]])

In [17]:
arr1[:,:2]

array([[12, 19],
       [ 2,  1]])

In [18]:
arr<5

array([ True, False, False, False, False, False])

In [19]:
(arr>3)& (arr<5)

array([False, False, False, False, False, False])

In [20]:
arr1<5

array([[False, False,  True,  True, False, False],
       [ True,  True, False,  True, False, False]])

In [21]:
np.add(arr,2)

array([ 5, 11,  8,  7, 11, 14])

In [22]:
np.add(arr1,2)

array([[14, 21,  5,  6, 18, 20],
       [ 4,  3, 25,  6, 12, 28]])

In [23]:
np.subtract(arr1,2)

array([[10, 17,  1,  2, 14, 16],
       [ 0, -1, 21,  2,  8, 24]])

In [24]:
np.multiply(arr1,5)

array([[ 60,  95,  15,  20,  80,  90],
       [ 10,   5, 115,  20,  50, 130]])

In [25]:
np.divide(arr1,4)

array([[3.  , 4.75, 0.75, 1.  , 4.  , 4.5 ],
       [0.5 , 0.25, 5.75, 1.  , 2.5 , 6.5 ]])

In [26]:
np.power(arr,2)

array([  9,  81,  36,  25,  81, 144], dtype=int32)

In [27]:
arr=np.array([[1.1,2.3,6.8,8],[2.2,6,6.8,9.5]])
arr1=np.array([[9,3,6,8,5],[8,5,2,3,4]])
arr2=np.array([[9,3,6,8,5],[8,5,6,-3,5,]])

In [28]:
np.array_equal(arr2,arr1)

False

In [29]:
np.sqrt(25)

5.0

In [30]:
np.sqrt(arr2)

<ipython-input-30-aa262e2109e4>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr2)


array([[3.        , 1.73205081, 2.44948974, 2.82842712, 2.23606798],
       [2.82842712, 2.23606798, 2.44948974,        nan, 2.23606798]])

In [31]:
np.cos(arr2)

array([[-0.91113026, -0.9899925 ,  0.96017029, -0.14550003,  0.28366219],
       [-0.14550003,  0.28366219,  0.96017029, -0.9899925 ,  0.28366219]])

In [32]:
np.sin(90)

0.8939966636005579

In [33]:
np.log(arr2)

<ipython-input-33-0fb2bd2eb7ae>:1: RuntimeWarning: invalid value encountered in log
  np.log(arr2)


array([[2.19722458, 1.09861229, 1.79175947, 2.07944154, 1.60943791],
       [2.07944154, 1.60943791, 1.79175947,        nan, 1.60943791]])

In [34]:
np.abs(arr1)

array([[9, 3, 6, 8, 5],
       [8, 5, 2, 3, 4]])

In [35]:
np.ceil(arr)

array([[ 2.,  3.,  7.,  8.],
       [ 3.,  6.,  7., 10.]])

In [36]:
np.floor(arr)

array([[1., 2., 6., 8.],
       [2., 6., 6., 9.]])

In [37]:
np.round(arr)

array([[ 1.,  2.,  7.,  8.],
       [ 2.,  6.,  7., 10.]])

In [38]:
arr =np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
np.mean(arr,axis=1)

array([2.5, 6.5])

In [40]:
arr.min()

1

In [45]:
arr.max(axis=0)


array([5, 6, 7, 8])

In [46]:
arr=np.array([[3,4],[5,6]])

In [47]:
np.var(arr)

1.25

In [48]:
np.var(arr,axis=0)

array([1., 1.])

In [49]:
np.std(arr,axis=1)

array([0.5, 0.5])